In [1]:
!wget http://www.ats.ucla.edu/stat/data/binary.csv

--2019-05-24 15:03:04--  http://www.ats.ucla.edu/stat/data/binary.csv
Resolving www.ats.ucla.edu (www.ats.ucla.edu)... 128.97.141.26
Connecting to www.ats.ucla.edu (www.ats.ucla.edu)|128.97.141.26|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://stats.idre.ucla.edu/ [following]
--2019-05-24 15:03:05--  http://stats.idre.ucla.edu/
Resolving stats.idre.ucla.edu (stats.idre.ucla.edu)... 128.97.141.21
Connecting to stats.idre.ucla.edu (stats.idre.ucla.edu)|128.97.141.21|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://stats.idre.ucla.edu/ [following]
--2019-05-24 15:03:05--  https://stats.idre.ucla.edu/
Connecting to stats.idre.ucla.edu (stats.idre.ucla.edu)|128.97.141.21|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘binary.csv’

binary.csv              [ <=>                ]  23.24K  --.-KB/s    in 0.1s

2019-05-24 15:03:06 (169 KB/s) - ‘binary.csv’ saved [23799]

In [0]:
import numpy as np
import pandas as pd

In [0]:
admissions = pd.read_csv('binary.csv')

In [9]:
# Make dummy variables for rank
data = pd.concat([admissions, pd.get_dummies(admissions['rank'], prefix='rank')], axis = 1)
data.drop('rank', axis=1)

     admit  gre   gpa  rank_1  rank_2  rank_3  rank_4
0        0  380  3.61       0       0       1       0
1        1  660  3.67       0       0       1       0
2        1  800  4.00       1       0       0       0
3        1  640  3.19       0       0       0       1
4        0  520  2.93       0       0       0       1
5        1  760  3.00       0       1       0       0
6        1  560  2.98       1       0       0       0
7        0  400  3.08       0       1       0       0
8        1  540  3.39       0       0       1       0
9        0  700  3.92       0       1       0       0
10       0  800  4.00       0       0       0       1
11       0  440  3.22       1       0       0       0
12       1  760  4.00       1       0       0       0
13       0  700  3.08       0       1       0       0
14       1  700  4.00       1       0       0       0
15       0  480  3.44       0       0       1       0
16       0  780  3.87       0       0       0       1
17       0  360  2.56       0       0       1       0
18       0  800  3.75       0       1       0       0
19       1  540  3.81       1       0       0       0
20       0  500  3.17       0       0       1       0
21       1  660  3.63       0       1       0       0
22       0  600  2.82       0       0       0       1
23       0  680  3.19       0       0       0       1
24       1  760  3.35       0       1       0       0
25       1  800  3.66       1       0       0       0
26       1  620  3.61       1       0       0       0
27       1  520  3.74       0       0       0       1
28       1  780  3.22       0       1       0       0
29       0  520  3.29       1       0       0       0
..     ...  ...   ...     ...     ...     ...     ...
370      1  540  3.77       0       1       0       0
371      1  680  3.76       0       0       1       0
372      1  680  2.42       1       0       0       0
373      1  620  3.37       1       0       0       0
374      0  560  3.78       0       1       0       0
375      0  560  3.49       0       0       0       1
376      0  620  3.63       0       1       0       0
377      1  800  4.00       0       1       0       0
378      0  640  3.12       0       0       1       0
379      0  540  2.70       0       1       0       0
380      0  700  3.65       0       1       0       0
381      1  540  3.49       0       1       0       0
382      0  540  3.51       0       1       0       0
383      0  660  4.00       1       0       0       0
384      1  480  2.62       0       1       0       0
385      0  420  3.02       1       0       0       0
386      1  740  3.86       0       1       0       0
387      0  580  3.36       0       1       0       0
388      0  640  3.17       0       1       0       0
389      0  640  3.51       0       1       0       0
390      1  800  3.05       0       1       0       0
391      1  660  3.88       0       1       0       0
392      1  600  3.38       0       0       1       0
393      1  620  3.75       0       1       0       0
394      1  460  3.99       0       0       1       0
395      0  620  4.00       0       1       0       0
396      0  560  3.04       0       0       1       0
397      0  460  2.63       0       1       0       0
398      0  700  3.65       0       1       0       0
399      0  600  3.89       0       0       1       0

[400 rows x 7 columns]

In [20]:
# Standarize features
for field in ['gre','gpa']:
    mean, std = data[field].mean(), data[field].std()
    data.loc[:,field] = (data[field]-mean)/std
    
data

     admit       gre       gpa  rank  rank_1  rank_2  rank_3  rank_4
280      0  0.564820  1.419385     2       0       1       0       0
53       1  0.737815 -0.274800     2       0       1       0       0
147      0 -0.300153 -1.690834     3       0       0       1       0
312      0  0.564820  0.989517     3       0       0       1       0
199      0 -0.127158  0.989517     4       0       0       0       1
42       1  0.045836 -0.578236     2       0       1       0       0
18       0  1.775783  0.938944     2       0       1       0       0
129      0 -1.165126 -0.578236     4       0       0       0       1
296      0 -0.300153 -0.552949     1       1       0       0       0
389      0  0.391825  0.332072     2       0       1       0       0
128      0 -0.473148 -0.477090     2       0       1       0       0
137      0  0.910809  1.571103     3       0       0       1       0
49       0 -1.684110 -0.072509     3       0       0       1       0
249      0  0.391825  0.888372     3       0       0       1       0
126      1  0.045836  0.407931     1       1       0       0       0
212      0 -1.165126 -1.286253     2       0       1       0       0
377      1  1.775783  1.571103     2       0       1       0       0
119      0 -2.203094 -1.159821     3       0       0       1       0
281      0 -2.030100 -0.274800     3       0       0       1       0
248      0  0.737815  0.660795     3       0       0       1       0
124      0  1.083804  1.267667     3       0       0       1       0
73       0 -0.127158  1.571103     2       0       1       0       0
287      1  0.564820  0.812513     4       0       0       0       1
13       0  0.910809 -0.755240     2       0       1       0       0
349      0  0.218831 -1.336826     2       0       1       0       0
61       0 -0.300153 -0.148368     4       0       0       0       1
91       1  1.083804  0.660795     1       1       0       0       0
39       1 -0.646142 -1.766693     3       0       0       1       0
135      0 -0.819137  0.483790     3       0       0       1       0
251      0  0.218831 -0.426518     4       0       0       0       1
..     ...       ...       ...   ...     ...     ...     ...     ...
368      0 -0.127158  1.571103     1       1       0       0       0
105      1  1.256799 -1.033390     2       0       1       0       0
329      0 -0.819137 -1.134535     4       0       0       0       1
285      0  0.045836 -0.173654     4       0       0       0       1
159      0  0.910809  1.115949     3       0       0       1       0
166      0 -1.338121 -0.350659     4       0       0       0       1
112      0 -2.030100 -0.957531     3       0       0       1       0
45       1 -1.165126  0.180354     3       0       0       1       0
17       0 -2.030100 -2.070129     3       0       0       1       0
83       0 -1.857105 -1.185108     4       0       0       0       1
47       0 -0.819137 -1.033390     4       0       0       0       1
72       0 -0.992132  0.028636     4       0       0       0       1
337      0  0.218831 -0.729954     4       0       0       0       1
164      0 -0.127158 -0.198941     2       0       1       0       0
332      0 -1.511116 -1.058676     1       1       0       0       0
33       1  1.775783  1.571103     3       0       0       1       0
11       0 -1.338121 -0.401231     1       1       0       0       0
371      1  0.737815  0.964231     3       0       0       1       0
326      0  0.737815 -0.173654     2       0       1       0       0
139      1  0.045836  0.509077     1       1       0       0       0
150      1  1.775783  0.913658     1       1       0       0       0
221      0  0.737815  1.545816     3       0       0       1       0
244      0 -0.473148 -0.856385     1       1       0       0       0
263      1  0.218831  1.444671     3       0       0       1       0
82       0 -0.819137 -1.690834     2       0       1       0       0
90       0  0.910809  1.141235     2       0       1       0       0
132      0 -0.127158  0.053923     2       0       1       0       0
158      0  0.564820  0.281500     2       0       1       0       0
84       1 -0.819137  0.559649     3       0       0       1       0
378      0  0.391825 -0.654095     3       0       0       1       0

[234 rows x 8 columns]

In [0]:
# Split off random 10% of the data for testing
np.random.seed(42)
sample = np.random.choice(data.index, size=int(len(data)*0.9), replace = False)
data, test_data = data.loc[sample], data.drop(sample)

In [0]:
# Split into features and targets
features, targets = data.drop('admit', axis=1), data['admit']
features_test, targets_test = test_data.drop('admit', axis=1), test_data['admit']

In [0]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [0]:
# Using same seed to make debugging easier
np.random.seed(42)

In [0]:
n_records, n_features = features.shape
last_loss = None

In [0]:
# Initializing the weights
weights = np.random.normal(scale=1 / n_features**.5, size=n_features)

In [0]:
# Neural Network Hyperparameters
epochs = 1000
learnrate = 0.5

In [34]:
# Training and testing
for e in range(epochs):
    
    del_w = np.zeros(weights.shape)
    for x, y in zip(features.values, targets):
        # Looping through all records, x is the input, y is the target
        
        # Calculating the output, instead of calculating h before, calculating with output
        output = sigmoid(np.dot(x, weights))
        
        # Calculating the error
        error = y - output
        
        # Calculating the error term
        error_term = error * output * (1 - output)
        
        # The gradient descent step
        del_w += error_term * x
        
    # Updating the weights (Remember why I am dividing it with n_records)
    weights += learnrate * del_w / n_records
    
    # Printing out the mean square error on the training set
    if e % (epochs / 10) == 0:
        out = sigmoid(np.dot(features, weights))
        loss = np.mean((out - targets) ** 2)
        if last_loss and last_loss < loss:
            print("Train loss: ", loss, "  WARNING - Loss Increasing")
        else:
            print("Train loss: ", loss)
        last_loss = loss
        
# Calculate accuracy on test data
tes_out = sigmoid(np.dot(features_test, weights))
predictions = tes_out > 0.5
accuracy = np.mean(predictions == targets_test)
print("Prediction accuracy: {:.3f}".format(accuracy))

Train loss:  0.3104933253472141
Train loss:  0.19381128166408063
Train loss:  0.19266471023230788
Train loss:  0.1921130871300722
Train loss:  0.19183447551969718
Train loss:  0.19168874466228691
Train loss:  0.19160971919242084
Train loss:  0.19156546761051615
Train loss:  0.19154002063432127
Train loss:  0.19152507377427136
Prediction accuracy: 0.741